name: reviewdog
on: [pull_request]
jobs:
  yamllint:
    name: runner / yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: yamllint-github-pr-check
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
      - name: yamllint-github-check
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: warning
          path: '.'
          exclude: 'testdata'
      - name: yamllint-github-pr-review
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          path: '.'
          exclude: 'testdata'
